// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmgM8UkKSNW_LXNWDH11fMRh1uEwatNMY',
    appId: '1:147754585:web:1393910ad5d5e2d6c46b48',
    messagingSenderId: '147754585',
    projectId: 'lab06-b213d',
    authDomain: 'lab06-b213d.firebaseapp.com',
    storageBucket: 'lab06-b213d.appspot.com',
    measurementId: 'G-D7CBX1VGS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvxys5ZJDnUg7b__r5Jv-2ehas0nSI91Y',
    appId: '1:147754585:android:7dfba20fe10870c3c46b48',
    messagingSenderId: '147754585',
    projectId: 'lab06-b213d',
    storageBucket: 'lab06-b213d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3FHvSVmdIXLa2f8pFK_96SWLEHZyEwMY',
    appId: '1:147754585:ios:c753277935600060c46b48',
    messagingSenderId: '147754585',
    projectId: 'lab06-b213d',
    storageBucket: 'lab06-b213d.appspot.com',
    iosClientId: '147754585-g7fm4c3k85ros8h6cb0o1gltv768mhi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3FHvSVmdIXLa2f8pFK_96SWLEHZyEwMY',
    appId: '1:147754585:ios:c753277935600060c46b48',
    messagingSenderId: '147754585',
    projectId: 'lab06-b213d',
    storageBucket: 'lab06-b213d.appspot.com',
    iosClientId: '147754585-g7fm4c3k85ros8h6cb0o1gltv768mhi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab06',
  );
}
